"""query table

Revision ID: 6684d8fd3cba
Revises: d7d0a62c6a9f
Create Date: 2023-07-16 09:37:17.216891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6684d8fd3cba'
down_revision = 'd7d0a62c6a9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('query',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('query_terms', sa.String(length=240), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('query', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_query_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('query', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_query_timestamp'))

    op.drop_table('query')
    # ### end Alembic commands ###
